name: CI workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'graphenex/**'
  
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'graphenex/**'

#defaults:
#  run:
#    shell: bash


jobs:
  setup_linux:
    name: "Linux setup"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: update
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: 'install dependencies'
        run: |
          sudo apt install python3-pip
          python -m pip install --upgrade pip

      - name: 'install graphenex'
        run: python3 -m pip install graphenex

  linter_linux:
    name: "Linter check linux"
    runs-on: ubuntu-latest
    needs: setup_linux
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 'flake8 python linter'
        uses: py-actions/flake8@v2

  graphenex_actions_linux:
    name: "Actions on graphenex linux"
    runs-on: ubuntu-latest
    needs: setup_linux

    steps: 
    - name: 'run graphenex'
      run: python -m graphenex



  setup_windows:
    name: "Windows setup"
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 'install python' 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        
      - name: 'update pip'
        run: python -m pip install --upgrade pip

      - name: 'install graphenex'
        run: python3 -m pip install graphenex

  linter_windows:
    name: "Linter check windows"
    runs-on: windows-latest
    needs: setup_windows
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: 'flake8 python linter'
        uses: py-actions/flake8@v2

  graphenex_actions_windows:
    name: "Actions on graphenex windows"
    runs-on: windows-latest
    needs: setup_windows 
    steps: 
    - name: 'run graphenex'
      run: python -m graphenex


